### PR TITLE
Implemented SHI

### PR DESCRIPTION
**Pull request by emoon**
Part of https://github.com/marhel/r68k/issues/45

### CODE REVIEW

**Comment by marhel** [comment]
Please add at least one test of the resulting op code constants. It will help if refactoring the "component constants" which I had to do today for the ASL constants, when trying to implement LSL, ROL and ROXL.

**Comment by emoon** [comment]
Will do!

**Comment by emoon** [comment]
Do you mean tests likes these ones? https://github.com/emoon/r68k/blob/master/src/cpu/ops/handlers.rs#L1860

**Comment by marhel** [comment]
For some reason I don't see the lineline numbers on the phone, but I mean tests like correctly_defined_op_eori_32_di, just copying Musashis constant, to verify our definition.

**Comment by emoon** [comment]
Will do a new one that merges clean

**Pull request closed without merging**
